---
- name: Install and config metricbeat on web servers
  hosts: webservers 
  become: true
  tasks:
    - name: Download metricbeats dev file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
    
    - name: install .deb file using dpkg
      command: dpkg -i metricbeat-7.4.0-amd64.deb
       
    - name: copy metricbeats config file
      copy: 
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml
   
    - name: metricbeat enabling modules
      command: metricbeat modules enable docker 
    
    - name: Setup metricbeat
      command: metricbeat setup
  
    - name: start metricbeat service
      command: service metricbeat start

    - name: metricbeat service enabled on boot
      systemd:
        name: metricbeat
        enabled: yes
